management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
server:
  servlet:
    context-path: "/api"

logging:
  level:
    root: info
