management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
server:
  servlet:
    context-path: "/api"

logging:
  level:
    root: info

springdoc:
  packagesToScan: com.ggar.bills.rest
  pathsToMatch: /v1, /api/**, /api/actuator/**
  swagger-ui:
    path: /swagger-ui
  show-actuator: true
#  api-docs:
#    enabled: true
#    path: /api-docs
#    version: openapi_3_0